CREATE SEQUENCE DISPOSITIVOS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_DISPOSITIVOS (
    ID INTEGER DEFAULT DISPOSITIVOS_SEQ.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    ATIVO CHAR(1) CHECK (ATIVO IN ('Y','N')) NOT NULL,
    ULTIMA_ATUALIZACAO DATE NOT NULL
);